### ISSUE TITLE
Css tập phim và nút lên đầu trang

### ISSUE THREAD

**Issue by ziinno1** [phantom0803/ophim-theme-bptv#1]
Css tập phim hiển thị không đều và đẹp mắt đối với phim nhiều tập (ví dụ: Đảo Hải Tặc). Nút lên đầu trang không hoạt động.

**Comment by ziinno1** [comment]
![Uploading 8779672C-A2AA-4E5A-A5C2-0EE7EE3827EA.png…]()

**Comment by ziinno1** [comment]
![590FAB1C-4EF4-44F8-BC2B-E98350860A7D](https://user-images.githubusercontent.com/117053689/198918384-ce4ac0d6-cc6f-4ee4-8269-a30294b8e448.png)
![Uploading A39E4975-EAF1-40F8-8915-7873F2C83DCB.png…]()

**Comment by ziinno1** [comment]
![Uploading E7ABB5D4-1679-475B-A8C5-DF6DE289E0AD.png…]()

**Comment by ziinno1** [comment]
![Uploading 93A11221-E770-49CA-A557-36484F86CEB9.png…]()

**Comment by phantom0803** [comment]
Đã cập nhật vào v1.0.1
